spring:
  profiles: dev
  application:
    name: ConfigClient
server:
  port: 8081
eureka:
  client:
    service-url:
      # 从 eureka 查询和注册的地址
      defaultZone: http://eureka1:8761/eureka/
  instance:
    # 自定义服务显示的名称信息
    instance-id: ConfigClient:${server.port}
    # 鼠标放上去的时候可以显示ip 信息
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点,shutdown 默认是关闭的
    shutdown:
      enabled: true
info:
  application: 服务提供者:${server.port}
  # $ 符号取决于 pom.xml 文件的配置
  version: $project.version$
  app: $artifactId$
  conpany: $groupId$
  desc: $description$
